package com.stevedaydream.tenantapp.data

import android.util.Log
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.Query
import com.google.firebase.firestore.ktx.toObjects
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await
// Removed java.util.UUID as it's not directly used here, assumed to be part of Announcement data class

class AnnouncementRepository(
    private val announcementDao: AnnouncementDao, 
    private val coroutineScope: CoroutineScope // Injected CoroutineScope
) {

    private val firestore = FirebaseFirestore.getInstance()
    private val announcementsCollection = firestore.collection("announcements")

    init {
        listenForAllAnnouncements()
    }

    private fun listenForAllAnnouncements() {
        // Listener for all announcements, ordered by date
        announcementsCollection.orderBy("date", Query.Direction.DESCENDING)
            .addSnapshotListener { snapshot, error ->
                if (error != null) {
                    Log.e("AnnouncementRepo", "Listen failed for all announcements.", error)
                    return@addSnapshotListener
                }
                snapshot?.let {
                    val announcements = it.toObjects<Announcement>()
                    coroutineScope.launch { // Use the injected scope
                        announcementDao.insertOrUpdateAll(announcements)
                    }
                }
            }
    }

    /**
     * [讀取]
     * 取得公告資料流。本地資料由 Firestore 監聽器保持同步。
     */
    fun getAnnouncements(landlordCode: String?): Flow<List<Announcement>> {
        // Data is always read from the local DAO, which is updated by the listener.
        return if (landlordCode != null) {
            announcementDao.getGlobalAndByLandlordCode(landlordCode)
        } else {
            announcementDao.getAll()
        }
    }

    /**
     * [寫入]
     * 新增一筆公告。
     * ID is typically generated by Firestore or passed in; ensure Announcement handles ID generation or one is provided.
     */
    suspend fun insert(announcement: Announcement) {
        // Assuming announcement.id is either pre-set or will be set by Firestore (if using generated IDs)
        // If Firestore generates ID, fetch it back or ensure local insert handles conflict/update if ID becomes known later.
        // For simplicity with current structure, we assume ID is part of `announcement` object or handled by Firestore.
        val document = if (announcement.id.isBlank()) {
            announcementsCollection.document() // Generate new ID if blank
        } else {
            announcementsCollection.document(announcement.id)
        }
        val finalAnnouncement = if (announcement.id.isBlank()) announcement.copy(id = document.id) else announcement
        
        // 1. 操作雲端
        document.set(finalAnnouncement).await()
        // 2. 更新本地
        announcementDao.insert(finalAnnouncement) // Assumes insert uses OnConflictStrategy.REPLACE
    }

    /**
     * [修改]
     * 更新一筆公告。
     */
    suspend fun update(announcement: Announcement) {
        if (announcement.id.isBlank()) throw IllegalArgumentException("Announcement ID cannot be blank for update.")
        // 1. 操作雲端
        announcementsCollection.document(announcement.id).set(announcement).await()
        // 2. 更新本地
        announcementDao.update(announcement) // Or use insert with OnConflictStrategy.REPLACE
    }

    /**
     * [刪除]
     * 刪除一筆公告。
     */
    suspend fun delete(announcement: Announcement) {
        if (announcement.id.isBlank()) throw IllegalArgumentException("Announcement ID cannot be blank for delete.")
        // 1. 操作雲端
        announcementsCollection.document(announcement.id).delete().await()
        // 2. 更新本地
        announcementDao.delete(announcement)
    }
}